export const tabConfig = {
  experiences: [
    {
      title: "Frontend Engineer",
      time: "Jan 2024 - Oct 2024",
      image: "https://placehold.co/150",
      company: "Kapstan Infra",
      location: "Remote (India/USA)",
      roles: [
        "💻 Worked on a project that involved building a web application for a client.",
        "⚛️ Developed the frontend using React, Redux, and TypeScript.",
        "🔗 Worked with the backend team to integrate the frontend with the backend.",
      ],
    },
    {
      title: "Software Engineer",
      time: "Jan 2023 - Oct 2023",
      image: "https://placehold.co/150",
      company: "Kapstan Infraa",
      location: "Remote (India/USA)",
      roles: [
        "💻 Worked on a project that involved building a web application for a client.",
        "⚛️ Developed the frontend using React, Redux, and TypeScript.",
        "🔗 Worked with the backend team to integrate the frontend with the backend.",
      ],
    },
    {
      title: "Frontend Engineer",
      time: "Jan 2022 - Oct 2022",
      image: "https://placehold.co/150",
      company: "Kapstan Infraaa",
      location: "Remote (India/USA)",
      roles: [
        "💻 Worked on a project that involved building a web application for a client.",
        "⚛️ Developed the frontend using React, Redux, and TypeScript.",
        "🔗 Worked with the backend team to integrate the frontend with the backend.",
      ],
    },
  ],
  techStacks: [
    {
      title: "React JS",
      time: "5",
      speciality: [
        "♻️ Reusable Components",
        "🔄 State Management",
        "⚡ Performance Optimization",
        "🌍 SEO Friendly",
        "🧩 Functional Components",
        "🪝 Hooks",
      ],
      image: "/img/react.svg",
    },
    {
      title: "TypeScript",
      time: "5",
      speciality: [
        "🔍 Type Safety",
        "🧰 Generic Types",
        "🧩 Interface",
        "🔗 Union Types",
        "🔮 Type Inference",
        "🔧 Type Alias",
      ],
      image: "/img/typescript.svg",
    },
    {
      title: "HTML5",
      time: "5",
      speciality: [
        "🧱 Semantic Elements",
        "🔗 Hyperlinks",
        "🔍 Accessibility",
        "📝 Forms",
        "🎨 Styling",
        "🔧 Attributes",
      ],
      image: "/img/html5.svg",
    },
    {
      title: "CSS3",
      time: "5",
      speciality: [
        "🎨 Box Model",
        "🔗 Selectors",
        "🔍 Responsive Design",
        "🧩 Flexbox",
        "🪝 Grid",
        "🔧 Animations",
      ],
      image: "/img/css3.svg",
    },
    {
      title: "JavaScript",
      time: "5",
      speciality: [
        "📜 ES6+",
        "🔧 Functions",
        "🌍 Scope",
        "🔒 Closure",
        "🎈 Hoisting",
        "⏳ Promises",
      ],
      image: "/img/javascript.svg",
    },
    {
      title: "Node JS",
      time: "5",
      speciality: [
        "🚀 Express",
        "🔒 Security",
        "🔧 Middleware",
        "🔍 Routing",
        "🔗 REST API",
        "🔮 Authentication",
      ],
      image: "/img/nodejs.svg",
    },
  ],
  projects: [
    {
      title: "Project 1",
      time: "Jan 2024 - Oct 2024",
      screenshots: [
        "https://placehold.co/110",
        "https://placehold.co/120",
        "https://placehold.co/130",
        "https://placehold.co/140",
        "https://placehold.co/150",
      ],
      techStack: ["React", "Redux", "TypeScript"],
      duration: "10 months",
      role: "Frontend Engineer",
      responsibilities: [
        "Developed the frontend using React, Redux, and TypeScript.",
        "Worked with the backend team to integrate the frontend with the backend.",
      ],
      link: "https://www.google.com",
    },
  ],
  education: [
    {
      title: "Bachelor of Technology",
      time: "2018 - 2022",
      image: "https://placehold.co/150",
      institution: "Kapstan University",
      location: "India",
      degree: "B.Tech",
      description:
        "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.",
      duration: "3 years",
    },
  ],
};
